name: counter_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  dio: ^4.0.4
  pretty_dio_logger: ^1.2.0-beta-1
  connectivity_plus: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.2
  mocktail: ^0.2.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
