name: flutter_bloc_login
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.16.0 <3.0.0"
dependencies:
  bloc_concurrency: "^0.2.0"
  flutter:
    sdk: flutter
  flutter_bloc: "^8.0.1"
  formz: any
  go_router: "^3.0.2"
  http: "^0.13.0"
  equatable: "^2.0.3"
  stream_transform: "^2.0.0"
  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository
  r_dart_library: 0.4.0-nullsafety.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: "^1.0.0"
flutter:
  uses-material-design: true
flr:
  core_version: 3.2.0
  dartfmt_line_length: 80
  assets: []
  fonts: []
